all: handout autograder
.PHONY: all handout autograder

LABDIR = `basename $(CURDIR)`_handout

FILES = sumarrayrows.c sumarraycols.c sumarray3d.c README.md Makefile .gitignore

#generate the lab for student distribution in subdir handout
handout:
	make -k clean
	rm -rf $(LABDIR)
	mkdir $(LABDIR)
	cp $(FILES) $(LABDIR)

	
clean:
	make -k clean
	rm -rf $(LABDIR)
#	(cd autograder; make clean)
	
