#!/usr/bin/env bash

# Set up autograder files
cp /autograder/submission/barrier.c /autograder/source/
cp /autograder/submission/barrier.h /autograder/source/
cd /autograder/source

python3 run_tests.py
