all: solution

SOLUTIONDIR = `basename $(CURDIR)`_solution
FILES = hello.c

# Generate the solution for the lab in a subdirectory solution.
solution:
	rm -rf $(SOLUTIONDIR)
	mkdir $(SOLUTIONDIR)
	unifdef -USTUDENT -o $(SOLUTIONDIR)/$(FILES) $(FILES); test "$$?" -eq 1
	
clean:
	rm -rf $(SOLUTIONDIR)
