#!/usr/bin/env bash

cp /autograder/submission/*.c /autograder/source/

# Run make with -k so it continues to compile next file even if a file fails
cd /autograder/source && make -k &> compile_output.txt

python3 hwtest.py ALL
mv /autograder/source/results.json /autograder/results/results.json
