all: solution

SOLUTIONDIR = `basename $(CURDIR)`_solution
FILES = pointers2.c

# Generate the solution for the lab in the subdirectory `solution`.
solution:
	rm -rf $(SOLUTIONDIR)
	mkdir $(SOLUTIONDIR)
	unifdef -USTUDENT -o $(SOLUTIONDIR)/pointers2.c pointers2.c; test "$$?" -eq 1
	
clean:
	rm -rf $(SOLUTIONDIR)
